
pipeline:
  setup:
    image: node:12-alpine
    secrets: [ jfrog_artifactory_token ]
    when:
      event: push
    commands:
      - npm config set //npm.daznplatform.com/:_authToken $JFROG_ARTIFACTORY_TOKEN
      - npm ci
      - npm run postinstall
      - npm run build

  lint:
    image: node:12-alpine
    group: test
    when:
      event: push
    commands:
      - npm run lint
  test-12:
    image: node:12-alpine
    group: test
    when:
      event: push
    commands:
      - npm test
  test-10:
    image: node:10-alpine
    group: test
    when:
      event: push
    commands:
      - npm test

  new-version:
    image: node:12
    secrets:
      - source: github_token
        target: gh_token
    when:
      event: push
      branch: master
    commands:
      - git config --global user.email "dazn-bot@dazn.com"
      - git config --global user.name "DAZN Bot"
      - npm run new-version

  npm-auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_token ]
    when:
      event: push
      branch: master

  publish:
    image: node:12
    secrets: [ jfrog_artifactory_token ]
    when:
      event: push
      branch: master
    commands:
      - npm config set //npm.daznplatform.com/:_authToken $JFROG_ARTIFACTORY_TOKEN
      - git config --global user.email "dazn-bot@dazn.com"
      - git config --global user.name "DAZN Bot"
      - git add .npmrc
      - "git commit -m \"ci(drone): tmp commit npmrc changes\""
      - npm run publish
