name: Build + Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run postinstall
      - run: npm run build
      - run: npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run lint


  release:
    runs-on: ubuntu-latest
    needs: [ test, lint ]
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run postinstall
      - run: npm run build
      - name: Setup Git
        run: |
          git config --global user.email "dazn-bot@dazn.com"
          git config --global user.name "DAZN Bot"
      - run: npm run new-version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run publish
